apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30005
  selector:
    name: result-app-pod
    app: demo-voting-app